# Generated by Django 3.1.1 on 2020-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
