# Generated by Django 3.1.1 on 2020-09-11 11:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('faq', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('chat_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='questionset',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='مقدار استفاده'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='question',
            field=models.TextField(verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='رتبه'),
        ),
    ]
